vich_uploader:
    db_driver: orm

    mappings:
        bacouploader:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        user_avatars:
              uri_prefix: /uploads/avatar
              upload_destination: '%kernel.project_dir%/public/uploads/avatar'
              namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
              inject_on_load: false
              delete_on_update: true
              delete_on_remove: true
