controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

    # config/routes.yaml
#app_user_profile:
#    path: '/user/{username}'
#    controller: App\Controller\UserController::profile

app_user_profile:
    path: '/user/{id}'
    controller: App\Controller\UserController::profile
    requirements:
        id: \d+  # Questo assicura che id sia interpretato come intero

app_faq:
  path: /faq
  controller: App\Controller\FaqController::faq


import_cities:
    path: /import-cities
    controller: App\Controller\CittaController::importCities

app_user_edit:
    path: '/user/{id}/edit'
    controller: App\Controller\UserController::edit
    requirements:
        id: \d+
